myapp/urls.py
from django.urls import path,re_path

from django.contrib.auth import views as auth_views
from . import views
app_name = 'myapp'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('sign/',views.signin,name="sign"),
    path('refer/',views.refer_fun,name="refer"),
    path("ranklist/",views.ranklist,name="ranklist"),
    path('sendmail/',views.sendmail,name="sendmail"),
    re_path(r'^register/(?P<refer_code>[\w\-]+)/$',views.register,name="register"),
]

refer/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('',views.home,name="home"),
    path('aboutme',views.about,name="about"),
]

myapp/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User):

    def __str__(self):
        return "@{}".format(self.username)
#class Referal(models.Model):

##    refer_by = models.CharField(max_length=25)
    #refer_used_by = models.ForeignKey('auth.User',on_delete='CASCADE',related_name='fo')
class UserResult(models.Model):
    refer_by=models.OneToOneField('auth.User',on_delete='CASCADE',related_name='result')
    point=models.IntegerField()

myapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core import validators


class UserCreateForm(UserCreationForm):

    class Meta:
        fields=('username','email','password1','password2','first_name','last_name')
        model=get_user_model()
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['first_name'].label = "Your First Name"
        self.fields['first_name'].label = "Your Last Name"
        self.fields['email'].label = "Email Address"
        self.fields['password1'].label = "Password"
        self.fields['password2'].label = "Confirm Password"
class FormName(forms.Form):
    Referal_Code=forms.CharField()

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
from . import models
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('myapp:login')
    template_name = 'accounts/signup.html'

def signin(request):

    return render(request,'accounts/sign.html',{})

def refer_fun(request):

    form=forms.FormName()
    da=False
    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            code=form.cleaned_data['Referal_Code']

            try:
                go = User.objects.get(username=code)
            except:
                go=False
            if go:
                return HttpResponseRedirect(reverse('myapp:register',kwargs={'refer_code':go}))
            da="Referal Code Does Not Match"




    return render(request,"accounts/form.html",{"form":form,"da":da})
def register(request,refer_code):

    registered = False
    if request.method == "POST":
        user_form = forms.UserCreateForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            refer_used=user_form.cleaned_data['username']
            user.set_password(user.password)
            user.save()
            ob1=User.objects.get(username=refer_code)
            try:
                a1=ob1.result
                a1.point=a1.point+100
                a1.save()
            except:
                a=models.UserResult(refer_by=ob1,point=100)
                a.save()


            return HttpResponseRedirect(reverse('myapp:sendmail'))

        else:
            print(user_form.errors)
    else:

        user_form =forms.UserCreateForm()

    return render(request,'accounts/signup.html',{
                                    'form':user_form,
                                    'registered':registered,
    })
def ranklist(request):
    data=models.UserResult.objects.all().order_by('-point')

    return render(request,'ranklist.html',{'data':data,})
def sendmail(request):
    ob=User.objects.latest('pk')
    subject = 'Welcome to HoneyMint'
    #message="Hi"
    message = 'Welcome'+ob.first_name+"\n"+'Your Referal Code is '+str(ob.username)+"\n"+"Share this link amoung your friend "+str("http://127.0.0.1:8000/myapp/signup/")+str(ob.username)
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [str(ob.email),]
    send_mail( subject, message, email_from, recipient_list )

    return HttpResponseRedirect(reverse('myapp:login'))

refer/views.py
from django.shortcuts import render
from myapp import models
from django.contrib.auth.models import User
def home(request):


    return render(request,'index.html',{})

def about(request):

    return render(request,'aboutus.html',{})

templates/aboutus.html
{% extends "index.html" %}
{% load staticfiles %}
{% block body %}


<div class="card mb-3 jumbotron container" style="max-width: 810px;margin-top:100px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{% static 'saurabh.jpg' %}" class="card-img" alt="Not Available">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Saurabh Singh</h5>
        <p class="card-text">I am student of B.Tech in IET Lucknow. I am a competative programmer and Django Backend developer. </p>
        <p class="card-text">View my <b><a href="https://drive.google.com/open?id=1roJYX1PWxb40j-gQaMuPMwxNLeo54vFP" style="color:black">CV</a></b> </p>
        <p class="card-text">Visit my <b><a href="https://github.com/97saurabh" style="color:black">GitHub</a></b> account to view my work.</p>
        <p class="card-text">Connect via <b><a href="https://www.linkedin.com/in/saurabh-singh-ba5301158/" style="color:black">LinkdIn</a></b>.</p>
        <p class="card-text">Mail me at <u>saurabh12singh11@gmail.com</u></p>
        <p class="card-text">Call me at <u>9140872959</u></p>


      </div>
    </div>
  </div>
</div>





{% endblock %}

templates/accounts/form.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block body %}


<div class="container jumbotron" style="margin-top:100px;max-width: 540px;" >



  <h1 style="font-family:'Montserrat';text-align:center;">Put Your Code</h1>

  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if da %}
    <h6>{{ da }}</h6>
    {% endif %}
    <input type="submit" class="btn btn-primary" value="Enter" style="margin-left:200px;">
  </form>

</div>




{% endblock %}

templates/accounts/login.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block body %}



<div class="container jumbotron" style="margin-top:100px;" >



  <h1 style="font-family:'Montserrat';text-align:center;">Login</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="LogIn" style="margin-left:500px;">
  </form>

</div>




{% endblock %}

templates/accounts/sign.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block body %}



<div class="container jumbotron" style="margin-top:100px;" >


<a href="{% url 'myapp:refer' %}" role="button" class="btn btn-primary" style="margin-left:250px;">With Referal Code</a>
<a href="{% url 'myapp:signup' %}" role="button" class="btn btn-primary" style="margin-left:250px;">Without Referal Code</a>

</div>




{% endblock %}

templates/accounts/signup.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block body %}



<div class="container jumbotron" style="margin-top:100px;">



  <h1 style="font-family:'Montserrat';text-align:center;">SignUp</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class="btn btn-primary" value="SignUp" style="margin-left:500px;">
  </form>

</div>




{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HoneyMint</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>
  <body style="background-color: Black;">



    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" style="margin-top:10px;">
  <a class="navbar-brand" href="{% url 'home' %}">HoneyMint</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:ranklist' %}">Rank List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">Who am i?</a>
      </li>
    </ul>

    <ul class="navbar-nav mr-right">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:logout' %}">LogOut</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:login' %}">LogIn</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:sign' %}">SignUp</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block body %}
<div class="container jumbotron" style="margin-top:100px;">
      {% if user.is_authenticated %}
      <h3>Welcome..</h3>
      <p>{{ user.first_name }} Your current score is {{ user.result.point }}. For assurance of your win share your link to friend or tell them to signup using your Username.






      {% else %}

      <h2>Welcome to HoneyMint</h2>
      <p>We are going to launch our new product.On the opening of our product we are organizing a competition.
        You have to SignUp first and ask your friends to do same.
        Your no of referal count will help to win.
        Go and SignUp now and invite your friends to SignUp using your referal Code.



      {% endif %}
</div>





  {% if not user.is_authenticated %}
  <div class="container jumbotron">
  <h3>Scenario-</h3>
  A client approached us to create a social media campaign for the launch of their new talcum powder. Let’s call the drink “Honeymint”. The client also advised they are on a limited budget.
  The creatives met up with the client and came up with an idea.
  The idea is to build a simple competition webpage within the client’s website that encourages people to spread the news about the new product. Users arrive at the page and sign up a form. After a successful sign up, they get one entry for the competition. At that point, they also have an option to share the sign up link. Every successful sign up referred via the link will give extra competition entries to the original link poster. There is no limit to the number of entries that a person can enter. So the idea is: The more entries you have, the higher your chance to win the prize.
  The prize is 100 bottles of Honeymint.
  The top 10 persons with the most entries will win the prize.
  Requirements:
  <ul>
  <li>	The new webpage is to be launched 3 months from today.
  <li>The duration of the competition will be 1 month from the day it is launched. After that, the webpage will be removed.
  <li>The webpage will consist of text, graphical elements and a sign up form.
  <li>The sign up form will consist of the following compulsory fields: First name, Last name, Mobile Number and Email Address.
  <li>When the form is submitted, the user will receive an EDM (Electronic Direct Mail) with an option to post a special link to the competition page from his/her Facebook or twitter account.
  <li>When people arrive to the competition page via the special link and signs up the form. The original poster will get one more extra entry for the competition.
  <li>After the competition has expired, provide a list of winners to the client.
  </ul>
</div>
  {% endif %}






{% endblock %}






  </body>
</html>

templates/ranklist.html
{% extends 'index.html' %}
{% load bootstrap3 %}




{% block body %}

<div class="jumbotron container" style="margin-top:100px;"">




  <ul class="list-group" style="font-family: 'Josefin Sans', sans-serif;">
      <li><h1 style="margin-left:12em;">Rank List</h1></li>
  </ul>

    <table  border="1" style="padding: 15px; border-spacing: 5px;font-family: 'Abel', sans-serif;" class="table table-hover">
                      <tr style="text-align:center;">
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Points</th>

                      </tr>

                      {% for i in data %}
                      <tr style="text-align:center;">
                        <td>{{ i.refer_by.first_name }} {{ i.refer_by.last_name }}</td>
                        <td>{{ i.refer_by.email }}</td>
                        <td>{{  i.point }}</td>

                      </tr>

                      {% endfor %}
    </table>












</div>




{% endblock %}